{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubepod.serviceAccountName" . }}
  namespace: {{ .Values.namespace| default .Release.Namespace }}
  labels:
    {{- include "kubepod.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
