# Default values for kubepod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kubepod
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.2.0-im-555069e

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: "kubepod"

aws:
  region: "us-east-1"
eksConfig:
  clusterName: "eks-cluster"
logLevel: "debug"

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789102:role/eks-access-role
  name: ""

podAnnotations: {}

securityContext:
  runAsUser: 0

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 50m
   memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
